// Model-output: Claude Fable 5.1

import { describe, expect, it } from "vitest";
import { DEFAULT_OPTIONS, type ProjectOptions } from "./config.ts";
import { render, type RenderInput } from "./render.ts";

const BASE: RenderInput = { options_text: "", options: DEFAULT_OPTIONS, project_sections: [], web_design_body: "" };

/** @returns The rendered file for the defaults overridden by `patch`. */
function render_with(patch: Partial<ProjectOptions>, input: Partial<RenderInput> = {}): Promise<string> {
	return render({ ...BASE, ...input, options: { ...DEFAULT_OPTIONS, ...patch } });
}

describe("render", () => {
	it("starts with the header, carrying the options text", async () => {
		const text = await render_with({}, { options_text: "\nlanguages = [\"rust\"]\n" });
		expect(text.startsWith("<!-- for-agents\n# This file is generated by `for-agents`")).toBe(true);
		expect(text).toContain("run `for-agents update .` in this repo");
		expect(text).toContain("\n\nlanguages = [\"rust\"]\n-->\n\n# Environment\n");
	});

	it("omits Node material for a non-Node project", async () => {
		const text = await render_with({ languages: ["python"] });
		expect(text).not.toContain("# Working with Node projects");
		expect(text).not.toContain("# Libraries to use");
		expect(text).toContain("\nWhen writing _any_ kind of code:\n\n- Think about invariants");
		expect(text).not.toContain("curlies");
		expect(text).not.toContain("For CREATE TABLE");
	});

	it("includes Node material for a TypeScript project", async () => {
		const text = await render_with({ languages: ["typescript"], checks: ["pnpm"] });
		expect(text).toContain("# Working with Node projects\n\nnpm sux");
		expect(text).toContain("When writing _any_ kind of code, including for the above:");
		expect(text).toContain("Minutae:\n\n- Use the { } curlies even for one-statement blocks.\n- Block contents");
		expect(text).toContain("# Libraries to use\n\n- `ayy`");
		expect(text).not.toContain("`effection`");
		expect(text).toContain("\tpnpm check # runs tsc\n");
		expect(text).toContain("\n\nThen automatically commit your changes with this commit template:");
	});

	it("uses svelte-check for Svelte and adds effection and extra libraries when asked", async () => {
		const text = await render_with({ languages: ["svelte"], effection: true, libraries_extra: ["`ventojs` for templating.", "`ws` for sockets."], checks: ["pnpm"] });
		expect(text).toContain("\tpnpm check # runs svelte-check\n");
		expect(text).toContain("when observing the system.\n- `effection`. We like structured programming");
		expect(text).toContain("(unless needed).\n- `ventojs` for templating.\n- `ws` for sockets.\n- `vitest` for unit tests");
	});

	it("adds the brace rules for C and the DDL paragraph for SQL", async () => {
		const text = await render_with({ languages: ["c", "sql"] });
		expect(text).toContain("- Use the { } curlies");
		expect(text).not.toContain("# Working with Node projects");
		expect(text).toContain("User loves AskUserQuestion.\n\nFor CREATE TABLE i.e. DDL work");
	});

	it("puts the sandbox note in the hostname bullet and extra tools after uv", async () => {
		const text = await render_with({ sandbox_note: "you're unable to hit production", tools_extra: ["ffmpeg", "nm"] });
		expect(text).toContain("- If it ends in \"clank\", you're unable to hit production; run whatever commands you need.\n- If any other hostname");
		expect(text).toContain(", uv, ffmpeg, nm, psql, ");
		expect(await render_with({})).toContain("- If it ends in \"clank\", run whatever commands you need.");
	});

	it("renders the web design variants", async () => {
		expect(await render_with({})).not.toContain("# Web design");
		const dark = await render_with({ web_design: "2010", color_scheme: "dark" });
		expect(dark).toContain("# Web design\n\nSet your mind to 2010 styling");
		expect(dark).toContain("native HTML elements.\n\nThis is a \"dark mode\"-only project");
		expect(await render_with({ web_design: "2010", color_scheme: "light" })).toContain("\"light mode\"-only project");
		expect(await render_with({ web_design: "2010" })).toContain("native HTML elements.\n\nPlease keep things working well in both light mode and dark mode.\n\nWrite CSS");
		const custom = await render_with({ web_design: "custom" }, { web_design_body: "Bespoke.\n\n- rules" });
		expect(custom).toContain("# Web design\n\nBespoke.\n\n- rules\n\n# Programming thoughts");
		expect(custom).not.toContain("2010 styling");
	});

	it("orders the check steps as given", async () => {
		const text = await render_with({ checks: ["sqlx", "cargo"] });
		expect(text).toContain("# After making changes\n\nOnly if any sqlx queries were modified:\n\n\t./make-sqlx-data\n\nAt the workspace root:\n\n\tcargo test\n\nThen automatically commit");
		expect(await render_with({})).toContain("# After making changes\n\nAutomatically commit your changes");
	});

	it("replaces the commit template for nixpkgs-style commits, keeping the checks", async () => {
		const text = await render_with({ commit_style: "nixpkgs" });
		expect(text).toContain("# After making changes\n\nAutomatically commit them as per the standard nixpkgs style for doing commits. Check the git log for a particular directory if uncertain.\n\n# Codex code review after each commit");
		expect(text).not.toContain("<prompt>");
		const checked = await render_with({ commit_style: "nixpkgs", checks: ["cargo"] });
		expect(checked).toContain("# After making changes\n\nAt the workspace root:\n\n\tcargo test\n\nThen automatically commit them as per the standard nixpkgs style");
	});

	it("ignores extra.web_design for a custom design, which is the project's own already", async () => {
		const custom = await render_with({ web_design: "custom", extra: { ...DEFAULT_OPTIONS.extra, web_design: "(Note.)" } }, { web_design_body: "Bespoke." });
		expect(custom).toContain("# Web design\n\nBespoke.\n\n# Programming thoughts");
		expect(custom).not.toContain("(Note.)");
	});

	it("appends the extra text at each slot", async () => {
		const text = await render_with({
			languages:  ["typescript"],
			web_design: "2010",
			checks:     ["pnpm"],
			extra: {
				environment:      "A questdb is around.",
				code_conventions: "Match upstream style.",
				web_design:       "(Existing code violates this.)",
				checks:           "plus the bank steps above when bank/ changed.",
			},
		});
		expect(text).toContain("edit this file.\n\nA questdb is around.\n\n# Avoid consuming");
		expect(text).toContain("keep existing lines.\n\n# Code conventions");
		expect(text).toContain("to align things.\n\nMatch upstream style.\n\n# Libraries to use");
		expect(text).toContain("written by humans.\n\n(Existing code violates this.)\n\n# Programming thoughts");
		expect(text).toContain("\tpnpm test  # runs vitest\n\nplus the bank steps above when bank/ changed.\n\nThen automatically commit");
	});

	it("places project sections between Programming thoughts and After making changes, verbatim", async () => {
		const sections = [{ heading: "Project map", body: "- a/\n- b/" }, { heading: "The app", body: "Text.\n\n\n\n```\n\n\n# code\n```" }];
		const text = await render_with({}, { project_sections: sections });
		expect(text).toContain("User loves AskUserQuestion.\n\n# Project map\n\n- a/\n- b/\n\n# The app\n\nText.\n\n\n\n```\n\n\n# code\n```\n\n# After making changes\n");
	});

	it("carries the options text through verbatim, blank lines included", async () => {
		const options_text = "languages = [\"rust\"]\n\n\n[extra]\nchecks = \"\"\"\nA\n\n\nB\"\"\"";
		const text = await render_with({}, { options_text });
		expect(text).toContain(`# overwritten.\n\n${options_text}\n-->\n\n# Environment\n`);
	});

	it("never leaves runs of blank lines and ends with one newline", async () => {
		for (const text of [await render_with({}), await render_with({ languages: ["typescript", "c", "sql"], web_design: "2010", checks: ["pnpm"] })]) {
			expect(text).not.toMatch(/\n{3,}/);
			expect(text.endsWith("\n")).toBe(true);
			expect(text.endsWith("\n\n")).toBe(false);
		}
	});
});
